# -*- coding: utf-8 -*-
"""app_starbucks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hike1HKL_qc_jYrRM5whKUKbLlILTTZ2
"""

import streamlit as st
import joblib
import numpy as np

# Title
st.title("Starbucks MLR Prediction Model")

# Load the model (fixed path)
model_path = "Starbucks_MLR.pkl"
model = joblib.load(model_path)

# Input fields
amount_prepaid = st.number_input("Amount of Prepaid Card", min_value=0.0, step=0.1)
age = st.number_input("Age", min_value=0, step=1)
days_per_month = st.number_input("Days per Month at Starbucks", min_value=0, step=1)
income = st.number_input("Income", min_value=0.0, step=100.0)

# Predict button
if st.button("Predict"):
    features = np.array([[amount_prepaid, age, days_per_month, income]])
    prediction = model.predict(features)
    st.write("Predicted Cups of Coffee per Day:", round(prediction[0], 2))